/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ROwnerRepoRouteImport } from './routes/r.$owner.$repo'
import { Route as ROwnerRepoIndexRouteImport } from './routes/r.$owner.$repo.index'
import { Route as ROwnerRepoArchitectureRouteImport } from './routes/r.$owner.$repo.architecture'
import { Route as ROwnerRepoOverviewRouteImport } from './routes/r.$owner.$repo.overview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ROwnerRepoRoute = ROwnerRepoRouteImport.update({
  id: '/r/$owner/$repo',
  path: '/r/$owner/$repo',
  getParentRoute: () => rootRouteImport,
} as any)
const ROwnerRepoIndexRoute = ROwnerRepoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ROwnerRepoRoute,
} as any)
const ROwnerRepoArchitectureRoute = ROwnerRepoArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => ROwnerRepoRoute,
} as any)
const ROwnerRepoOverviewRoute = ROwnerRepoOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => ROwnerRepoRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/r/$owner/$repo': typeof ROwnerRepoRouteWithChildren
  '/r/$owner/$repo/architecture': typeof ROwnerRepoArchitectureRoute
  '/r/$owner/$repo/overview': typeof ROwnerRepoOverviewRoute
  '/r/$owner/$repo/': typeof ROwnerRepoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/r/$owner/$repo/architecture': typeof ROwnerRepoArchitectureRoute
  '/r/$owner/$repo/overview': typeof ROwnerRepoOverviewRoute
  '/r/$owner/$repo': typeof ROwnerRepoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/r/$owner/$repo': typeof ROwnerRepoRouteWithChildren
  '/r/$owner/$repo/architecture': typeof ROwnerRepoArchitectureRoute
  '/r/$owner/$repo/overview': typeof ROwnerRepoOverviewRoute
  '/r/$owner/$repo/': typeof ROwnerRepoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/r/$owner/$repo'
    | '/r/$owner/$repo/architecture'
    | '/r/$owner/$repo/overview'
    | '/r/$owner/$repo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/r/$owner/$repo/architecture'
    | '/r/$owner/$repo/overview'
    | '/r/$owner/$repo'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/r/$owner/$repo'
    | '/r/$owner/$repo/architecture'
    | '/r/$owner/$repo/overview'
    | '/r/$owner/$repo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ROwnerRepoRoute: typeof ROwnerRepoRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$owner/$repo': {
      id: '/r/$owner/$repo'
      path: '/r/$owner/$repo'
      fullPath: '/r/$owner/$repo'
      preLoaderRoute: typeof ROwnerRepoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$owner/$repo/': {
      id: '/r/$owner/$repo/'
      path: '/'
      fullPath: '/r/$owner/$repo/'
      preLoaderRoute: typeof ROwnerRepoIndexRouteImport
      parentRoute: typeof ROwnerRepoRoute
    }
    '/r/$owner/$repo/architecture': {
      id: '/r/$owner/$repo/architecture'
      path: '/architecture'
      fullPath: '/r/$owner/$repo/architecture'
      preLoaderRoute: typeof ROwnerRepoArchitectureRouteImport
      parentRoute: typeof ROwnerRepoRoute
    }
    '/r/$owner/$repo/overview': {
      id: '/r/$owner/$repo/overview'
      path: '/overview'
      fullPath: '/r/$owner/$repo/overview'
      preLoaderRoute: typeof ROwnerRepoOverviewRouteImport
      parentRoute: typeof ROwnerRepoRoute
    }
  }
}

interface ROwnerRepoRouteChildren {
  ROwnerRepoArchitectureRoute: typeof ROwnerRepoArchitectureRoute
  ROwnerRepoOverviewRoute: typeof ROwnerRepoOverviewRoute
  ROwnerRepoIndexRoute: typeof ROwnerRepoIndexRoute
}

const ROwnerRepoRouteChildren: ROwnerRepoRouteChildren = {
  ROwnerRepoArchitectureRoute: ROwnerRepoArchitectureRoute,
  ROwnerRepoOverviewRoute: ROwnerRepoOverviewRoute,
  ROwnerRepoIndexRoute: ROwnerRepoIndexRoute,
}

const ROwnerRepoRouteWithChildren = ROwnerRepoRoute._addFileChildren(
  ROwnerRepoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ROwnerRepoRoute: ROwnerRepoRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
